name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          cd webapp
          dotnet publish -c Release -o package
          cd package
          zip -r ../package.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: webapp/package.zip
        
  deploy_dev:
    needs: [build]
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package
          path: webapp/package.zip
      - name: Run a multi-line script
        run: |
          ls
          echo dev
          
  deploy_prod:
    needs: [deploy_dev]
    environment: Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo prod
