name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          cd webapp
          dotnet publish -c Release -o package
          cd package
          zip -r ../package.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: webapp/package.zip
          
      - uses: actions/upload-artifact@v3
        with:
          name: iac
          path: app-service.bicep
        
  deploy_dev:
    needs: [build]
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package
          path: ./
          
      - uses: actions/download-artifact@v3
        with:
          name: iac
          path: ./
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run IaC
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create -g betabit-workshop-dev -f ./app-service.bicep -p appname=bbws-site-dev

      - name: Deploy app
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp deploy --resource-group betabit-workshop-dev --name bbws-site-dev --src-path ./package.zip
              
  deploy_prod:
    needs: [deploy_dev]
    environment: Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: package
          path: ./
          
      - uses: actions/download-artifact@v3
        with:
          name: iac
          path: ./
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run IaC
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create -g betabit-workshop-prod -f ./app-service.bicep -p appname=bbws-site-prod

      - name: Deploy app
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp deploy --resource-group betabit-workshop-prod --name bbws-site-prod --src-path ./package.zip
