name: Deloy Azure Storage
on: workflow_dispatch

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    environment: 
      name: Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az deployment group create -g betabit-workshop-dev -f ./storage.bicep 
          
