name: devdvs_CI-CD-Pipeline

on:
  push:
#    branches: [ "main" ]
  pull_request:
#    branches: [ "main" ]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo build
      - name: checkout repository
        uses: actions/checkout@v3
      - name: build artifact
        run: |
          cd webapp
          dotnet publish -c Release -o package
          cd package
          zip -r ../package.zip .

      - name: upload package
        uses: actions/upload-artifact@v3        
        with:          
          name: package          
          path: webapp/package.zip
      - name: upload bicep
        uses: actions/upload-artifact@v3        
        with:          
          name: iac          
          path: app-service.bicep
       
  deploy_dev:
    needs: [build]
    environment: 
      name: Dev
      url: https://bbws-site-dev.azurewebsites.net
    runs-on: ubuntu-latest
    steps:
      - run: echo create infra
      - run: echo deploy!
      - name: download package
        uses: actions/download-artifact@v3
        with:
          name: package
          path: ./package.zip  
      - name: download bicep
        uses: actions/download-artifact@v3
        with:
          name: iac          
          path: app-service.bicep
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Run IaC
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create -g betabit-workshop-dev -f ./app-service.bicep -p appname=bbws-site-dev
      - name: Deploy app
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp deploy --resource-group betabit-workshop-dev --name bbws-site-dev --src-path ./package.zip

#
#      - run: |
#            client-id: ${{ secrets.AZURE_CLIENT_ID }}
#            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#            az deployment group create -g betabit-workshop-dev -f ./app-service.bicep -p appname=bbws-site-dev      
#            az webapp deploy --resource-group betabit-workshop-dev --name bbws-site-dev --src-path ./package.zip
#      #download package and iac artifact
#      
#      # do an azure cli login
#      # use these ids
#                client-id: ${{ secrets.AZURE_CLIENT_ID }}
#                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#
#       run this az cli command to create the webapp
#            az deployment group create -g betabit-workshop-dev -f ./app-service.bicep -p appname=bbws-site-dev
#
#       run this az cli command to deploy the webapp
#        az webapp deploy --resource-group betabit-workshop-dev --name bbws-site-dev --src-path ./package.zip
             
